language: c
compiler: gcc-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - valgrind

before_script:
  - cc --version
  - cd src/

script: make && make test