language: c
compiler: gcc-4.7

before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.2.tar.gz -O /tmp/casper.tar.gz
  - tar -

before_script:
  - export CC=gcc-4.8
  - gcc --version
  - cd src/

script: make && make test